### ISSUE TITLE
关于“发现”和“首页”的功能设置

### ISSUE THREAD

**Issue by westcounty** [micourse2015/micourseDocuments#1]
我想把“发现”和“首页”的名字对调，内容不变，大家觉得怎么样…… 
也就是首页里显示的是一个大列表，里面是最近上传的一些文件，发现里是用户自己关注的内容。

**Comment by vboar** [comment]
目前web的首页是大列表（可选择排序方式、筛选条件），动态里面是用户关注的。

**Comment by westcounty** [comment]
嗯，那APP也这么改了。
